version: "3"
services:
  nginx:
    image: nginx:latest # 镜像`nginx:latest`
    restart: always    # 指定容器退出后的重启策略为始终重启
    container_name: nginx  # 容器名为'nginx'
    ports: # 映射端口
      - 8080:80
    volumes:  # 数据卷挂载路径设置,将本机目录映射到容器目录
      - ./conf/:/etc/nginx/conf.d/
      - ./html/:/usr/share/nginx/html/
      - ./../logs/nginx:/var/log/nginx/
    environment: # 设置环境变量,相当于docker run命令中的-e
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
